baseURL = 'https://n1bsd.github.io/'
languageCode = 'en-us'
title = 'N1BSD'
theme = 'nostyleplease'

[permalinks]
  posts = "/:slug/"

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = true
    codeFences         = true
    guessSyntax        = true
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'rrt'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  [params.theme_config]
    appearance        = "dark"
    back_home_text    = "<--"
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = false

  [[params.entries]]
    [params.entries.post_list]
      limit          = 0
      show_more      = false
      show_more_text = ""
      show_more_url  = ""
